use strict;
use warnings;
use Test::More;
use File::Spec;

use FindBin;

my $root = File::Spec->catdir($FindBin::Bin, '..');
my $app = _read(File::Spec->catfile($root, 'lib', 'DesertCMS', 'App.pm'));
my $http = _read(File::Spec->catfile($root, 'lib', 'DesertCMS', 'HTTP.pm'));
my $theme = _read(File::Spec->catfile($root, 'lib', 'DesertCMS', 'Theme.pm'));
my $site_css = _read(File::Spec->catfile($root, 'themes', 'default', 'assets', 'site.css'));

like($site_css, qr{--focus-ring: color-mix}, 'public theme defines a shared focus ring token');
like($site_css, qr{padding: max\(12px, var\(--site-header-padding-y}, 'public header keeps a usable default vertical rhythm');
like($site_css, qr/\.site-menu-toggle \{[\s\S]*?border: 1px solid var\(--line\)/, 'public mobile menu button has a visible hit target');
like($site_css, qr/\.theme-toggle \{[\s\S]*?border: 1px solid var\(--line\)/, 'public theme toggle uses the same icon-button treatment');
like($site_css, qr/\.site-header nav a\.active,\s*\.site-header nav a\[aria-current="page"\][^{]*\{[\s\S]*?background: color-mix/, 'public mobile nav has a clear active state');
like($site_css, qr{\.docs-table \{ display: block; max-width: 100%; overflow-x: auto; white-space: nowrap; \}}, 'public docs tables scroll safely on narrow screens');
like($site_css, qr{\.docs-layout \{ display: grid; grid-template-columns: 1fr;}, 'public docs page uses a full-width navigation/content flow');
like($site_css, qr{\.docs-nav \{ grid-template-columns: 1fr; gap: 16px;}, 'public docs nav uses one full-width grouped nav flow');
like($site_css, qr{\.docs-nav-group \{ grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 220px\), 1fr\)\);}, 'public docs nav groups spread links into roomy responsive columns');
like($site_css, qr{\.docs-sidebar \{ position: static; width: 100%; \}}, 'public docs nav is not sticky or constrained like a sidebar');
like($site_css, qr{\.docs-hub-panel \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(160px, 1fr\)\);}, 'public docs Resource Hub summary uses responsive stat cards');
like($site_css, qr{\.docs-meta-strip \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(140px, 1fr\)\);}, 'public docs Resource Hub metadata wraps safely');
like($site_css, qr{DesertCMS component upgrade: public event ticket wrapping}, 'public Events ticket controls have an upgrade marker');
like($site_css, qr{\.event-ticket-option \{ grid-template-columns: minmax\(0, 1fr\) minmax\(min\(100%, 320px\), auto\); \}}, 'public Events ticket rows use a bounded action column');
like($site_css, qr{\.event-ticket-form \{ min-width: 0; grid-template-columns: minmax\(70px, 92px\) minmax\(0, 1fr\) minmax\(112px, auto\); \}}, 'public Events ticket forms use shrink-safe tracks');
like($site_css, qr{\@media \(max-width: 760px\) \{\s*\.event-ticket-option,\s*\.event-ticket-form \{ grid-template-columns: 1fr; \}}s, 'public Events ticket rows stack before narrow tablet layouts crowd');
like($site_css, qr{\.module-action-link,\s*\.shop-button,\s*\.rights-option button,\s*\.event-ticket-form button \{[\s\S]*?white-space: normal; overflow-wrap: anywhere;}, 'public module action buttons wrap long labels');
like($site_css, qr{DesertCMS component upgrade: public donations}, 'public Donations pages have a dedicated upgrade marker');
like($site_css, qr{\.donation-detail-layout \{ display: grid; grid-template-columns: minmax\(0, 1fr\) minmax\(min\(100%, 300px\), 380px\);}, 'public Donations detail keeps story and donate panel in stable tracks');
like($site_css, qr{\.donation-amount-grid \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 106px\), 1fr\)\);}, 'public Donations amount options wrap as buttons');
like($site_css, qr{\.public-upload-preview \{ grid-template-columns: 38px minmax\(0, 1fr\); \}}, 'public upload previews compact cleanly on phones');
like($site_css, qr{\.link-card:hover,\s*\.resource-card:hover,\s*\.content-ref-card:hover,\s*\.social-link:hover}m, 'public cards share hover treatment');
like($site_css, qr/\.slippy-map button \{[\s\S]*?min-width: 36px/, 'public map controls keep a readable tap target');
like($site_css, qr/\.map-popup small \{[\s\S]*?text-transform: uppercase/, 'public map popup has a location-kind badge style');
like($site_css, qr/\.showcase-resource-badge \{[\s\S]*?aspect-ratio: 4 \/ 3/, 'public Showcase resource cards keep stable preview dimensions');
like($theme, qr{_ensure_responsive_visual_polish_css}, 'theme installer upgrades existing editable theme copies');
like($theme, qr{DesertCMS component upgrade: responsive visual polish}, 'theme upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_docs_nav_layout_css}, 'theme installer upgrades existing docs nav layout');
like($theme, qr{DesertCMS component upgrade: docs nav layout}, 'docs nav layout upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_docs_nav_comfort_css}, 'theme installer upgrades existing docs nav comfort layout');
like($theme, qr{DesertCMS component upgrade: docs nav comfort layout}, 'docs nav comfort upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_docs_resource_hub_css}, 'theme installer upgrades existing docs Resource Hub layout');
like($theme, qr{DesertCMS component upgrade: docs resource hub}, 'docs Resource Hub upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_public_event_ticket_wrap_css}, 'theme installer upgrades existing public Events ticket controls');
like($theme, qr{DesertCMS component upgrade: public event ticket wrapping}, 'public Events ticket wrapping upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_donations_css}, 'theme installer upgrades existing public Donations layout');
like($theme, qr{DesertCMS component upgrade: public donations}, 'public Donations upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_public_map_tap_target_css}, 'theme installer upgrades existing map controls');
like($theme, qr{_ensure_map_locations_css}, 'theme installer upgrades existing map location-kind CSS');
like($theme, qr{_ensure_map_locations_js}, 'theme installer upgrades existing map location-kind script');
like($theme, qr{DesertCMS component upgrade: map location kinds}, 'map location-kind upgrade block is marked to avoid duplicate appends');
like($theme, qr{_ensure_showcase_css}, 'theme installer upgrades existing Showcase resource card styles');
like($theme, qr{DesertCMS component upgrade: showcase resource cards}, 'Showcase resource card upgrade block is marked to avoid duplicate appends');

like($app, qr{--focus-ring: color-mix}, 'admin theme defines a shared focus ring token');
like($app, qr/\.topbar nav a\.active,\s*\.topbar nav a\[aria-current="page"\][^{]*\{ border-color: color-mix/, 'admin mobile nav has a clear active state');
like($app, qr/\.admin-card-table tr \{[\s\S]*?box-shadow: 0 6px 18px/, 'admin mobile table cards have a consistent card surface');
like($app, qr{\.notice-close \{ width: 30px; max-width: 30px; min-width: 30px; \}}, 'admin phone button rule does not stretch notice close buttons');
like($app, qr{\.icon-link,\s*\.icon-link--button,\s*\.icon-button,\s*\.rich-tool-button}m, 'admin phone button rule exempts icon/editor controls');
like($app, qr/\.settings-preview \{[\s\S]*?display: grid[\s\S]*?gap: 5px/, 'admin settings previews stack long values cleanly');
like($app, qr/\.preview-mode-bar \{ min-width: 0; max-width: 100%;[\s\S]*?flex-wrap: wrap;/, 'admin preview mode bars wrap compact controls');
like($app, qr/\.preview-mode-bar button \{ min-width: 0; max-width: 100%;[\s\S]*?min-height: 34px[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin preview mode buttons keep a readable wrapped tap target');
like($app, qr/button \{ max-width: 100%; min-width: 0;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin buttons wrap long labels inside their containers');
like($app, qr/\.button-link \{ max-width: 100%; min-width: 0;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin link-buttons wrap long labels inside their containers');
like($app, qr/\.split \{ min-width: 0;[\s\S]*?flex-wrap: wrap;/, 'admin split headers wrap action groups instead of squeezing text');
like($app, qr/\.button-row \{ min-width: 0;[\s\S]*?flex-wrap: wrap;/, 'admin button rows wrap long grouped actions');
like($app, qr/\.row-actions \{ min-width: 0;[\s\S]*?flex-wrap: wrap;/, 'admin row actions wrap safely');
like($app, qr/\.settings-section-nav \{[\s\S]*?align-items: stretch;[\s\S]*?flex-wrap: wrap;/, 'admin settings nav lays long section lists into wrapped tiles');
like($app, qr/\.settings-section-nav button \{ flex: 1 1 132px;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin settings nav items wrap long labels');
like($app, qr/\.editor-nav \{ min-width: 0;[\s\S]*?flex-wrap: wrap;/, 'admin editor/account nav containers can shrink before wrapping');
like($app, qr/\.editor-nav a \{ min-width: 0; max-width: 100%;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin editor/account nav links wrap long labels inside their boxes');
like($app, qr/\.module-setup-nav \{ display: grid; gap: 8px; align-items: start;[\s\S]*?padding: 8px; \}/, 'admin module setup nav uses a compact grouped chip layout');
like($app, qr/\.module-setup-nav > \.module-setup-nav-home \{ width: fit-content; min-height: 34px;[\s\S]*?display: inline-flex;[\s\S]*?overflow-wrap: anywhere; \}/, 'admin module setup nav renders a compact clickable Modules/Features parent');
like($app, qr/\.module-setup-nav > \.module-setup-nav-home strong \{[\s\S]*?text-transform: uppercase; \}/, 'admin module setup parent label keeps the section name prominent');
like($app, qr/\.module-setup-nav > \.module-setup-nav-home small \{[\s\S]*?text-transform: none; \}/, 'admin module setup parent label names the catalog');
like($app, qr/\.module-setup-nav > \.module-setup-nav-home span \{ display: none; \}/, 'admin module setup parent hides technical parent metadata from the visible nav');
like($app, qr/\.module-setup-nav-group \{ min-width: 0; display: grid; grid-template-columns: minmax\(112px, auto\) minmax\(0, 1fr\);[\s\S]*?border: 0; background: transparent; \}/, 'admin module setup groups avoid oversized framed boxes');
like($app, qr/\.module-setup-nav-links \{ min-width: 0; display: flex; gap: 6px; flex-wrap: wrap; \}/, 'admin module setup links render as wrapping chips');
like($app, qr/\.module-setup-nav \.module-setup-nav-links a \{ flex: 0 1 auto; min-width: 0; min-height: 32px;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin module setup child links wrap long module labels');
like($app, qr/\.module-setup-nav \.module-setup-nav-links a \{ flex: 1 1 min\(100%, 132px\); min-height: 40px; \}/, 'admin module setup chips expand into touch-friendly rows on small screens');
like($app, qr/\@media \(max-width: 1180px\) and \(min-width: 821px\) \{[\s\S]*?\.contributor-topbar nav \{ order: 4;/, 'contributor product nav collapses earlier than master admin nav');
like($app, qr/desktopQuery = adminTopbar && adminTopbar\.classList\.contains\('contributor-topbar'\)[\s\S]*?\(min-width: 1181px\)[\s\S]*?\(min-width: 821px\)/, 'admin menu resize logic uses the contributor-specific desktop breakpoint');
like($app, qr/\.media-filter-tabs \{ min-width: 0; display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 142px\), 1fr\)\);/, 'admin media filter tabs use responsive tiles before the mobile breakpoint');
like($app, qr/\.media-filter-tabs strong \{ flex: 0 0 auto; min-width: 26px; max-width: 100%;[\s\S]*?overflow-wrap: anywhere; \}/, 'admin media filter counts stay inside wrapped filter tiles');
like($app, qr/\.media-search-form \{ min-width: 0; display: grid; grid-template-columns: minmax\(min\(100%, 280px\), 1fr\) repeat\(2, minmax\(116px, auto\)\);/, 'admin media search toolbar avoids fixed-width overflow');
like($app, qr/\.media-organization-filters \{ min-width: 0; display: grid; grid-template-columns: repeat\(2, minmax\(min\(100%, 180px\), 1fr\)\) repeat\(2, minmax\(136px, auto\)\);/, 'admin media organization filters wrap dense controls cleanly');
like($app, qr/\.media-bulk-toolbar \{ min-width: 0; display: grid; grid-template-columns: minmax\(min\(100%, 220px\), 1fr\) minmax\(min\(100%, 220px\), 280px\) minmax\(128px, auto\);/, 'admin media bulk toolbar has flexible action tracks');
like($app, qr/\.media-bulk-heading strong \{ max-width: 100%;[\s\S]*?white-space: normal; overflow-wrap: anywhere; \}/, 'admin media selected-count pill wraps instead of forcing toolbar overflow');
like($app, qr/\.shop-filter-bar \{ min-width: 0; display: grid; grid-template-columns: minmax\(min\(100%, 190px\), 280px\) minmax\(min\(100%, 220px\), 360px\) minmax\(92px, auto\) minmax\(92px, auto\);/, 'admin Shop / Catalog filter toolbar uses flexible tracks');
like($app, qr/\.shop-filter-count \{ min-height: 34px;[\s\S]*?white-space: normal; overflow-wrap: anywhere; \}/, 'admin Shop / Catalog filter count wraps safely');
like($app, qr/\.visual-block-toolbar \{ min-width: 0; position: sticky;[\s\S]*?flex-wrap: wrap;/, 'admin visual block toolbar can shrink before wrapping');
like($app, qr/\.visual-block-toolbar button \{ min-width: 0; max-width: 100%;[\s\S]*?white-space: normal; overflow-wrap: anywhere; \}/, 'admin visual block toolbar buttons wrap long block labels');
like($app, qr/\.section-insert-control \{ min-width: min\(100%, 260px\); max-width: 100%; flex: 1 1 320px; display: grid; grid-template-columns: minmax\(0, 1fr\) minmax\(82px, auto\);/, 'admin reusable section insert control uses shrink-safe tracks');
like($app, qr/\.visual-block-settings \{ min-width: 0; position: absolute;[\s\S]*?flex-wrap: wrap;/, 'admin visual block settings toolbar can shrink and wrap');
like($app, qr/\.visual-block-settings--rich \{ position: static; width: 100%; max-width: 100%; display: none;[\s\S]*?flex-wrap: wrap;/, 'admin rich text block settings use an inline wrapping toolbar');
like($app, qr/\.visual-block\.is-editing \.visual-block-settings--rich \{ display: flex;[\s\S]*?pointer-events: auto;/, 'admin rich text block settings become an inline toolbar while editing');
like($app, qr/\.visual-block-settings label span \{ min-width: 0;[\s\S]*?white-space: normal;[\s\S]*?overflow-wrap: anywhere; \}/, 'admin visual block setting labels wrap instead of forcing toolbar width');
like($app, qr/\.visual-block-settings input,\s*\.visual-block-settings select \{ width: min\(220px, 100%\); min-width: min\(116px, 100%\); max-width: 100%;/, 'admin visual block setting fields shrink inside compact toolbars');
like($app, qr/\.rich-text-tools \{ min-width: 0; max-width: 100%;[\s\S]*?flex-wrap: wrap; \}/, 'admin rich text tool groups wrap inside block settings');
like($app, qr/blockSettings\('Text', richTextToolbar\(block\.align\) \+ fontToolControls\(block\), 'visual-block-settings--rich visual-block-settings--wide', block\)/, 'admin rich text blocks render the inline rich toolbar instead of the side rail');
like($app, qr/\.settings-form-actions \{[\s\S]*?flex-wrap: wrap;[\s\S]*?gap: 10px;/, 'admin sticky form actions wrap instead of squeezing');
like($app, qr/label \{ min-width: 0; \}/, 'admin form labels can shrink inside dense setting grids');
like($app, qr/input, select, textarea \{ width: 100%; min-width: 0;/, 'admin form controls shrink within grid columns');
like($app, qr/\.field-row > \* \{ min-width: 0; \}/, 'admin field-row children can shrink instead of forcing overflow');
like($app, qr/\.checkbox-field \{ min-width: 0;[\s\S]*?align-items: start;/, 'admin checkbox rows align multiline labels from the top');
like($app, qr/\.blueprint-checkbox-grid \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 240px\), 1fr\)\);/, 'admin long checkbox setting lists use responsive columns');
like($app, qr/\.service-plan-feature-groups \{ display: grid; gap: 14px; \}/, 'admin service plan feature controls are grouped instead of one long list');
like($app, qr/\.service-plan-feature-grid \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 240px\), 1fr\)\); gap: 10px; \}/, 'admin service plan feature groups use responsive columns');
like($app, qr/\.service-plan-feature-option small \{ display: block;[\s\S]*?overflow-wrap: anywhere; \}/, 'admin service plan feature descriptions wrap inside cards');
like($app, qr/\.workflow-grid \{ min-width: 0; display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(100%, 230px\), 1fr\)\); gap: 14px; \}/, 'admin workflow card grids avoid fixed 230px overflow in narrow panels');
like($app, qr/\@media \(max-width: 430px\) \{[\s\S]*?\.billing-plan-features li \{ grid-template-columns: 1fr; align-items: start; \}[\s\S]*?\.billing-plan-features strong \{ text-align: left; \}/, 'billing plan feature rows stack label and value on phones');
like($app, qr/\.settings-form label,\s*\.settings-form \.muted,\s*\.settings-form small,\s*\.settings-form code,\s*\.settings-form a \{ min-width: 0; max-width: 100%; overflow-wrap: anywhere; word-break: break-word; \}/, 'admin settings form helper text and inline values wrap safely');
like($app, qr/\.settings-subsection > \* \{ min-width: 0; \}/, 'admin settings subsection children can shrink');
like($app, qr/\.content-table td p,\s*\.content-table td li,\s*\.content-table td code,\s*\.content-table td small,\s*\.content-table td strong,\s*\.content-table td span \{ min-width: 0; overflow-wrap: anywhere; word-break: break-word; \}/, 'admin table cell children wrap safely');
like($app, qr/\.admin-empty-state > \* \{ min-width: 0; max-width: 100%; overflow-wrap: anywhere; \}/, 'admin empty-state children wrap safely');
like($app, qr/\.settings-subsection p,\s*\.settings-subsection li,\s*\.settings-subsection dd,\s*\.settings-subsection dt,\s*\.settings-subsection strong,\s*\.settings-subsection em \{ min-width: 0; overflow-wrap: anywhere; word-break: break-word; \}/, 'admin settings subsection body text wraps safely');
like($app, qr/\.settings-subsection dl,\s*\.settings-subsection details,\s*\.settings-subsection summary \{ min-width: 0; max-width: 100%; \}/, 'admin settings details and definition lists can shrink');
like($app, qr/\.settings-subsection pre,\s*\.settings-form pre,\s*\.panel pre \{ max-width: 100%; overflow: auto; white-space: pre-wrap; overflow-wrap: anywhere; \}/, 'admin preformatted blocks wrap or scroll safely');
like($app, qr/\.notice > \* \{ min-width: 0; max-width: 100%; \}/, 'admin notice children can shrink beside dismiss controls');
like($app, qr/\.connection-status \{ min-width: 0;[\s\S]*?overflow-wrap: anywhere;/, 'admin connection status cards wrap provider messages safely');
like($app, qr/\.status-pill \{ box-sizing: border-box; max-width: 100%; min-width: 0;[\s\S]*?word-break: break-word;/, 'admin status pills wrap long states safely');
like($app, qr/\.health-list div \{ min-width: 0;[\s\S]*?display: grid;/, 'admin health cards allow long status content to shrink');
like($app, qr/\.metric-card > \* \{ min-width: 0; \}/, 'admin metric card children can shrink within cards');
like($app, qr/\.workflow-card span,\s*\.workflow-card strong,\s*\.workflow-card p,\s*\.workflow-card small \{ min-width: 0; overflow-wrap: anywhere; \}/, 'admin workflow cards wrap all text children');
like($app, qr/\.provider-readiness-detail-grid \{ display: grid; grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/, 'admin provider readiness detail panels use responsive grid columns');
like($app, qr/\.provider-endpoint-row code \{ min-width: 0; max-width: 100%; white-space: normal; overflow-wrap: anywhere; word-break: break-word; \}/, 'admin provider webhook endpoint URLs wrap safely');
like($app, qr/\@media \(max-width: 1100px\) \{[\s\S]*?\.provider-readiness-detail-grid \{ grid-template-columns: 1fr; \}/, 'admin provider readiness panels collapse on narrower screens');
like($app, qr/\.master-maintenance-strip > \* \{ min-width: 0; \}/, 'admin master maintenance strip children can shrink');
like($app, qr/\.master-status-heading > div \{ min-width: 0; \}/, 'admin master status headings can shrink before wrapping');
like($app, qr/\.module-card code \{ max-width: 100%;[\s\S]*?white-space: normal; overflow-wrap: anywhere;/, 'admin module route/code pills wrap safely');
like($app, qr/\.module-card h2 \{ min-width: 0;[\s\S]*?overflow-wrap: anywhere;/, 'admin module headings wrap safely');

like($app, qr/\.donut-legend li strong \{ min-width: 0; overflow-wrap: anywhere; white-space: normal; \}/, 'admin donut legends wrap long labels instead of truncating them');
like($app, qr/\.upgrade-file-state \{ display: inline-flex;[\s\S]*?overflow-wrap: anywhere; white-space: normal; \}/, 'admin upgrade file state wraps long archive names');

like($http, qr{admin\.css\?v=\$admin_css_version}, 'admin CSS cache key is supplied from the rendered site settings');
like($http, qr{editor\.js\?v=20260705c}, 'admin JS cache key stays aligned with admin assets');
like($app, qr/'Cache-Control'\s*=>\s*'private, max-age=31536000, immutable'/, 'admin CSS can be cached behind the settings-derived asset key');

done_testing;

sub _read {
    my ($path) = @_;
    open my $fh, '<', $path or die "cannot read $path: $!";
    local $/;
    return <$fh>;
}
