#!/usr/bin/env perl

use strict;
use warnings;
use File::Path qw(make_path);
use File::Temp qw(tempfile);
use Getopt::Long qw(GetOptionsFromArray);

my %S = (
    app_user        => '_desertcms',
    app_group       => '_desertcms',
    app_root        => '/usr/local/www/desertcms',
    data_base       => '/var/desertcms-sites',
    public_base     => '/var/www/htdocs',
    source_admin_db => '/var/desertcms/desertcms.sqlite',
    source_config   => '/etc/desertcms.conf',
    owner_name      => '',
    owner_email     => '',
);

GetOptionsFromArray(
    \@ARGV,
    'site-id=s'        => \$S{site_id},
    'domain=s'         => \$S{domain},
    'site-name=s'      => \$S{site_name},
    'app-root=s'       => \$S{app_root},
    'data-base=s'      => \$S{data_base},
    'public-base=s'    => \$S{public_base},
    'source-admin-db=s'=> \$S{source_admin_db},
    'source-config=s'  => \$S{source_config},
    'owner-name=s'     => \$S{owner_name},
    'owner-email=s'    => \$S{owner_email},
) or die usage();

die usage() unless $S{site_id} && $S{domain};
die "site id must be lowercase letters, numbers, or hyphens\n" unless $S{site_id} =~ /\A[a-z0-9][a-z0-9-]{1,62}\z/;
die "domain contains unsafe characters\n" unless $S{domain} =~ /\A[a-z0-9.-]+\z/;
$S{site_name} ||= $S{domain};
$S{owner_name} ||= $S{site_name};

my $config_file = "/etc/desertcms-$S{site_id}.conf";
my $data_dir = "$S{data_base}/$S{site_id}";
my $public_root = "$S{public_base}/desertcms-$S{site_id}";
my $db_path = "$data_dir/desertcms.sqlite";

run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '750', $data_dir);
run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '750', "$data_dir/backups");
run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '750', "$data_dir/originals");
run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '750', "$data_dir/themes");
run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '750', "$data_dir/upgrades");
run('install', '-d', '-o', $S{app_user}, '-g', $S{app_group}, '-m', '755', $public_root);
run('chown', '-R', "$S{app_user}:$S{app_group}", $public_root);

write_file($config_file, <<"CONF");
# DesertCMS instance generated by tools/openbsd-provision-site.pl

site_name = $S{site_name}
site_url = https://$S{domain}

data_dir = $data_dir
db_path = $db_path
app_secret_file = $data_dir/app_secret
public_root = $public_root
originals_dir = $data_dir/originals
backup_dir = $data_dir/backups
theme_dir = $data_dir/themes
admin_asset_dir = $S{app_root}/admin/assets

session_cookie = desertcms_$S{site_id}_session
session_ttl_seconds = 7200
secure_cookies = 1

login_lockout_seconds = 900
login_max_failures = 5

image_public_max_width = 1600
image_public_quality = 82
image_tool = /usr/local/bin/vips
tar_tool = tar

analytics_enabled = 1
analytics_retention_days = 365
analytics_store_raw_ip = 1

contributor_site_id = $S{site_id}
contributor_domain = $S{domain}
contributor_owner_name = $S{owner_name}
contributor_owner_email = $S{owner_email}
master_config_path = $S{source_config}

module_shop_enabled = 0
commerce_model = disabled
shop_enabled = 0
CONF

run('chown', 'root:' . $S{app_group}, $config_file);
run('chmod', '640', $config_file);

run_as_app('env', "DESERTCMS_CONFIG=$config_file", 'perl', "$S{app_root}/bin/desertcms-maint.pl", 'init-db');
seed_admin($db_path, $S{source_admin_db});
run_as_app('env', "DESERTCMS_CONFIG=$config_file", 'perl', "$S{app_root}/bin/desertcms-maint.pl", 'rebuild');

print "provisioned $S{domain}\n";
print "config: $config_file\n";
print "public root: $public_root\n";

sub seed_admin {
    my ($dest_db, $source_db) = @_;
    return unless -f $source_db;
    my $source_db_sql = sql_quote($source_db);
    my $sql = <<"SQL";
ATTACH DATABASE $source_db_sql AS source;
INSERT INTO admin_users
    (username, email, role, password_hash, password_algo, created_at, updated_at, force_password_change, disabled_at)
SELECT username, email, 'owner', password_hash, password_algo, created_at, updated_at, 0, NULL
FROM source.admin_users
WHERE disabled_at IS NULL
  AND COALESCE(role, 'owner') = 'owner'
  AND NOT EXISTS (SELECT 1 FROM admin_users WHERE disabled_at IS NULL);
INSERT INTO settings (key, value, updated_at)
SELECT key, value, strftime('%s','now')
FROM source.settings
WHERE key IN ('postmark_from_email', 'postmark_server_token')
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at;
INSERT INTO settings (key, value, updated_at)
VALUES ('postmark_sender_mode', 'inherit', strftime('%s','now'))
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at;
SQL
    run_as_app('sqlite3', $dest_db, $sql);
}

sub sql_quote {
    my ($value) = @_;
    $value = '' unless defined $value;
    $value =~ s/'/''/g;
    return "'$value'";
}

sub run_as_app {
    my @cmd = @_;
    run('su', '-m', $S{app_user}, '-c', join(' ', map { shell_quote($_) } @cmd));
}

sub run {
    my @cmd = @_;
    my ($fh, $path) = tempfile('desertcms-cmd-XXXXXX', TMPDIR => 1, UNLINK => 1);
    my $pid = fork();
    my $label = join ' ', map { shell_quote($_) } @cmd;
    die "cannot fork for command: $label: $!\n" unless defined $pid;
    if ($pid == 0) {
        open STDOUT, '>&', $fh or die "cannot redirect stdout: $!\n";
        open STDERR, '>&', $fh or die "cannot redirect stderr: $!\n";
        exec @cmd or do {
            print STDERR "cannot exec $cmd[0]: $!\n";
            exit 127;
        };
    }
    waitpid($pid, 0);
    my $status = $?;
    seek $fh, 0, 0;
    local $/;
    my $output = <$fh>;
    $output = '' unless defined $output;
    close $fh;
    return if $status == 0;

    my $status_label = command_status_label($status);
    $output =~ s/\s+\z//;
    my $message = "command failed ($status_label): $label";
    $message .= "\n$output" if length $output;
    die "$message\n";
}

sub command_status_label {
    my ($status) = @_;
    return 'exec failed' if $status == -1;
    return 'signal ' . ($status & 127) if $status & 127;
    return 'exit ' . ($status >> 8);
}

sub write_file {
    my ($path, $body) = @_;
    open my $fh, '>', $path or die "cannot write $path: $!\n";
    print {$fh} $body;
    close $fh;
}

sub shell_quote {
    my ($value) = @_;
    $value = '' unless defined $value;
    $value =~ s/'/'\\''/g;
    return "'$value'";
}

sub usage {
    return <<"USAGE";
usage: $0 --site-id ID --domain DOMAIN [--site-name NAME] [--source-config /etc/desertcms.conf] [--owner-name NAME] [--owner-email EMAIL]
USAGE
}
